### PR TITLE
Release v3.0.0

### PR DESCRIPTION
**Pull request by DistantVoyager**

### CODE REVIEW

**Comment by 7AXEL** [comment]
Check out this project: https://github.com/7AXEL/Web2APK

**Comment by DistantVoyager** [comment]
Is there something I need to add to have the changelog CI step pass?

**Comment by glennmatthews** [comment]
that step is *supposed* to be skipped for PRs to `main`: https://github.com/nautobot/nautobot-app-secrets-providers/pull/135/files#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fR195-R197

**Comment by glennmatthews** [comment]
maybe because that code isn't actually in `main` yet?

**Comment by DistantVoyager** [comment]
@glennmatthews - oh! Let me cancel and reopen the PR. I accidentally initially opened it going to `develop` then fixed to `main`. Maybe that messed it up

**Pull request closed without merging**
